// list of fields for json2csv conversion

module.exports = [ 'id',
  'pokemon_id',
  'cp',
  'stamina',
  'stamina_max',
  'move_1',
  'move_2',
  'deployed_fort_id',
  'owner_name',
  'is_egg',
  'egg_km_walked_target',
  'egg_km_walked_start',
  'origin',
  'height_m',
  'weight_kg',
  'individual_attack',
  'individual_defense',
  'individual_stamina',
  'cp_multiplier',
  'pokeball',
  'captured_cell_id',
  'battles_attacked',
  'battles_defended',
  'egg_incubator_id',
  'creation_time_ms',
  'num_upgrades',
  'additional_cp_multiplier',
  'favorite',
  'nickname',
  'from_fort' ];