var json2csv = require('json2csv');
var fs = require('fs');
var fields = require('./fields.js')

var SRC_JSON = 'example.json' //[your filename here generated by running ```$> node index.js```]
var OUT_CSV =  'example.csv'//[your csv filename, where to put output]

var promisify = function (fn) {
	return function () {
		var args = [].slice.call(arguments)
		return new Promise(function (resolve, reject){
			fn.apply(null, args.concat(function (err, contents){
				if(err) return reject(err);
				resolve(contents)
			}))
		})
	}
}

var _json2csv = promisify(json2csv);

fs.readFile(SRC_JSON, 'utf8', function(err, data){
	 _json2csv({data: JSON.parse(data), fields: fields})
	 .then(function (result) {
	 	fs.writeFileSync(OUT_CSV, result);
	 });
});